### PR TITLE
Add Filter for Instance

### PR DESCRIPTION
**Pull request by X-Raym**
This allow to make all widget attributes variable and filterable.
For exemple: 'title_url' and 'title_link', according to a certain widget 'class'.

### CODE REVIEW

**Comment by X-Raym** [comment]
@bostondv Hi ! As you are now pushing UPW to WordPress 4.8, it would be nice if you could consider this pull request :) I use it since months and it is very useful. As it is only one filter, it doesn't have any performance issue.

**Comment by bostondv** [comment]
What do you think about adding `$this->id_base` as a second argument to the filter? otherwise looks good, thanks!

**Comment by X-Raym** [comment]
@bostondv the more arguments there is is better ! :)
thanks !

**Comment by X-Raym** [comment]
@bostondv Argument added!

**Comment by X-Raym** [comment]
@bostondv Thanks ! Glad to have participate in this plugin dev :P Can't wait for the release! 🎆

**Pull request merged**
